server:
  servlet:
    context-path: /bookshelf

spring:
  mvc:
    servlet:
      path: /api/v1
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: f72d401a
      database: bookshelf
      port: 27017
      host: localhost

springdoc:
  override-with-generic-response: false
  swagger-ui:
    path: /swagger